name: console-style
version: 0.0.2.0
category: Text, User Interfaces, Monad
description: Styled console text output using ANSI escape sequences.
synopsis: Styled console text output using ANSI escape sequences.
stability: experimental
author: Daniel Mendler <mail@daniel-mendler.de>
maintainer: Daniel Mendler <mail@daniel-mendler.de>
copyright: 2016 Daniel Mendler
license: MIT
github: minad/console-style

tested-with:
  GHC == 7.10.3,
  GHC == 8.0.1

ghc-options:
- -Wall

dependencies:
- base         >= 4.8 && < 5
- transformers >= 0.4 && < 0.6
- mtl          >= 2.2 && < 2.4

when:
  - condition: impl(ghc < 8.0)
    dependencies: semigroups >= 0.9 && < 1

library:
  source-dirs: src
